<footer class="bg-dark font-monospace text-white my_footer">
    <span class="text-center">&copy; By Mohammed Ali Choglay 2022 Version.0.0.1</span>
</footer>



<!-- Bootstrap core JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"  </script>


</body>
</html>