<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Brother League</title>
    <link rel="stylesheet" href="/CSS/bootstrap-5.1.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/CSS/myStyle.css">
</head>
<div class="jumbotron text-center bg-dark font-monospace text-white">
    <div class="container-fluid">
        <h1 class="navbar-text">The Brother Football League</h1>
    </div>
</div>
<body>
